title: Laranotify
description: A feature-rich laravel package that turns bootstrap notify jQuery plugin to dynamic notifications, alerts and blockables.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
